### PR TITLE
Enable custom search

### PR DESCRIPTION
**Pull request by ivoreis**
This PR enables custom search to be passed as a prop. This feature is similar to passing a custom pagination component.

### Usage

```js
// CustomSearch.js
import React from 'react';
import { SearchPropType } from '../utils/propTypes'

const CustomSearch = ({ searchString, searchRows, clearSearch }) => {
    return (
        <div className="react-collapsible-search">
            <input onChange={ searchRows } value={ searchString } placeholder="search"/>
            <button className="react-collapsible-clear" onClick={ clearSearch }>&#9587;</button>
        </div>
    );
};

export default CustomSearch
```

```js
// table.js
import CustomSearch from './CustomSearch'
import Table from '../table'

<Table showSearch={true}, CustomSearch={CustomSearch} />
```

### CODE REVIEW

**Comment by Salinn** [comment]
@ivoreis This looks pretty good and open to customizing it, any chance you can fix the coverage on the Table.js component?

**Comment by ivoreis** [comment]
@Salinn Yep. 👍 I'll do that.

**Comment by Salinn** [comment]
@ivoreis do you need a hand with the tests?

**Comment by Salinn** [comment]
@ivoreis do you need a hand with testing?

**Comment by ivoreis** [comment]
@Salinn I'm not using this anymore. I'll close the PR 👍 thanks for the help

**Pull request closed without merging**
