### PR TITLE
Add keyboard accessibility support for row expand and sorting

### PR DESCRIPTION
**Pull request by Suvra19**
This PR adds keyboard accessibility for Level AA Conformance to Web Content Accessibility Guidelines 2.0.

- Press "Enter" to expand and collapse rows
- Press "Enter" to sort columns (Also added tabIndex for focus)

@JonForest FYI

### CODE REVIEW

**Comment by Salinn** [comment]
Sorry I missed this, looks good!

**Comment by Salinn** [comment]
@Suvra19 can you resolve the conflict with the package json and I will merge and deploy this today?

**Comment by Suvra19** [comment]
> @Suvra19 can you resolve the conflict with the package json and I will merge and deploy this today?

Hi @Salinn, I have resolved the merge conflict and bumped the version. Or do you think we should keep the version as 1.0.2 as both changes will be part of the same release ?

**Comment by Salinn** [comment]
I think we should bump the version as it is a different feature

**Pull request merged**
