### PR TITLE
Add support for server delivered data and pagination with tests

### PR DESCRIPTION
**Pull request by Suvra19**
This PR enables the collapsing table to work from an external data source providing just the contents of the current page, rather than all the data up front. If this PR gets accepted, I am going to raise another PR to support server side column sorting.

We have been using both the server side pagination and sorting code in production without any issues so far. 

@JonForest FYI

### CODE REVIEW

**Comment by Suvra19** [comment]
> [Coverage Status](https://coveralls.io/builds/27246055)
> 
> Coverage decreased (-0.4%) to 99.632% when pulling **[98f9cc0](https://github.com/massmutual/react-collapsing-table/commit/98f9cc03e70490b7b994a9684fbc5312129a299a) on Suvra19:Enable-server-delivered-pages** into **[976a78d](https://github.com/massmutual/react-collapsing-table/commit/976a78d638c3b06307475d19099e21212eeb7a28) on massmutual:master**.

Will fix the test coverage.

**Comment by Salinn** [comment]
Looks good, can you bump the version in the package.json and I will merge and publish the version?

**Comment by Suvra19** [comment]
> Looks good, can you bump the version in the package.json and I will merge and publish the version?

Sounds good! I have bumped the version for server side pagination. I am going to follow up this PR with the server side sorting changes and some keyboard accessibility features.

**Comment by Salinn** [comment]
https://www.npmjs.com/package/react-collapsing-table/v/1.0.1

Sounds great! Here is the package

**Comment by Suvra19** [comment]
> https://www.npmjs.com/package/react-collapsing-table/v/1.0.1
> 
> Sounds great! Here is the package

Thank you!

**Pull request merged**
